### ISSUE TITLE
Issues with 0.0.14 (0.0.13 works)

### ISSUE THREAD

**Issue by MShawnDillon** [fresc81/node-winreg#27]
I am using Node 5.3.0, NPM 3.3.12... (also tried in Node 4.2.3, NPM 2.14.7)

The following simple functional test works in 0.0.13, but fails with the error shown below in 0.0.14:

```
> var winreg = require('winreg');
undefined
> var regKey = winreg({hive:winreg.HKLM});
undefined
> regKey.keys(function (err, data) {console.log(data);});
TypeError: Cannot read property 'on' of null
    at captureOutput (C:\Users\Shawn\winreg-test\node_modules\winreg\lib\registry.js:50:15)
    at Registry.keys (C:\Users\Shawn\winreg-test\node_modules\winreg\lib\registry.js:304:16)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
> .exit
```

**Comment by MShawnDillon** [comment]
Notice if you change line 298 in registry.js from this:

```
        stdio: [ 'ignore', 'pipe', 'ignore' ]
```

...to this...

```
        stdio: [ 'ignore', 'pipe', 'pipe' ]
```

... it will capture the stderr stream and work as expected.

I don't know what other effects this might have, though.

**Comment by justinmchase** [comment]
Related to #26 26

**Comment by justinmchase** [comment]
Thanks, will fix soon.

**Comment by fresc81** [comment]
just updated to version 0.0.15 which should fix your problem
