### ISSUE TITLE
Error when packaged in electron app

### ISSUE THREAD

**Issue by Ajeey** [fresc81/node-winreg#49]
Hi,

I get the following error when I run this library in electron(after I pack it into a .exe via electron-builder)

`{ Error\n    at mkErrorMsg (C:\\Users\\denimuser\\AppData\\Local\\Programs\\my-events\\resources\\app\\webpack:\\src\\uninstaller\\registry.js:111:12)\n    at ChildProcess.<anonymous> (C:\\Users\\denimuser\\AppData\\Local\\Programs\\my-events\\resources\\app\\webpack:\\src\\uninstaller\\registry.js:541:10)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:194:7)\n    at maybeClose (internal/child_process.js:899:16)\n    at Socket.<anonymous> (internal/child_process.js:342:11)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:191:7)\n    at Pipe._handle.close [as _onclose] (net.js:510:12) name: [Getter], message: [Getter], code: [Getter] }","timestamp":"2018-03-05 04:03:38"}`

**Comment by Galkon** [comment]
Bump. Need this resolved :(

**Comment by alanhamlett** [comment]
@gandarez @fresc81 so #55 fixes it but need to bump the version and release the fix?

**Comment by gandarez** [comment]
> @gandarez @fresc81 so #55 fixes it but need to bump the version and release the fix?

Exactly we need a new version of this ASAP.
